### ISSUE TITLE
Some problems in Windows 10 Education(21H2 Build 19044.2486)

### ISSUE THREAD

**Issue by jiansyuan** [Wapitiii/WSAppBak#5]
hi, I faced some problems when I pack the game Minecraft version1.19.51.
I am using Windows 10 Education(21H2 Build 19044.2486)(Windows Feature Experience Pack 120.2212.4190.0)

```
Please wait.. Creating '.appx' package file.


Unhandled Exception: System.ComponentModel.Win32Exception: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at WSAppBak.WSAppBak.RunProcess(String fileName, String args)
   at WSAppBak.WSAppBak.MakeAppx()
   at WSAppBak.WSAppBak.ReadArg()
   at WSAppBakExecute.Main(String[] args)
```

**Comment by Wapitiii** [comment]
Hello, sorry for the late reply. I've tried it on my Windows 10 device running 19044.2846 and it works fine without issues.
Have you already tried using an older version of WSAppBak? I'll try to rewrite the tool so that it will be better.

**Comment by naxl** [comment]
I want to address this issue, 

A issue with the application's manifest file or its dependencies is usually indicated by the error message "The application has failed to start because its side-by-side configuration is incorrect". There are other potential causes for this, such as:

- Inaccurate Manifest File: There could be missing or inaccurate information in the manifest file. Make sure that all required assemblies and their versions are accurately specified in the manifest file.

- Missing or Incorrect Dependencies: It is possible that the application is referring to assemblies that are either out-of-date or not present on the system.

- Corrupted System Files: It is possible that corrupted system files exist that are connected to the side-by-side setup. System file checks can be used to find and address these problems.

- Incorrect Installation: It's possible that the program or its dependencies weren't installed properly.

This problem also occurred to me. Upon closer inspection, I discovered that most of the time—on both my current and previous systems—the side-by-side configuration was altered inadvertently, and unless you run the corrected configuration once, it remains in the registry.

**Steps to produce trace : -** 

CMD : `sxstrace trace -logfile:sxstrace.etl`

Run WSAppBak

Press ENTER or : `sxstrace stoptrace`

CMD : `sxstrace parse -logfile:sxstrace.etl -outfile:sxstrace.txt`

You'll find the 'sxstrace.txt' on your Desktop!

PRODUCED
```
=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\Administrator\Downloads\WSAppBak\WSAppBak\MakeAppx.exe.Manifest
	AssemblyDirectory = C:\Users\Administrator\Downloads\WSAppBak\WSAppBak\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\Administrator\Downloads\WSAppBak\WSAppBak\MakeAppx.exe.Manifest.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 8: The value SXS_ASSEMBLY_VERSION of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
```

To fix this and all sort of manifest issues, use dummy placeholders in "MakeAppx.exe.manifest" File

```
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
  <assemblyIdentity
    version="1.0.0.0"
    processorArchitecture="amd64"
    name="MyAppName"
    type="win32"
  />
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level='asInvoker' uiAccess='false' />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        name="Microsoft.Windows.Build.Appx.AppxPackaging.dll"
        version="0.0.0.0"/>
    </dependentAssembly>
  </dependency>
</assembly>
```

Instead of : 

```
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
  <assemblyIdentity
    version=SXS_ASSEMBLY_VERSION
    processorArchitecture=SXS_PROCESSOR_ARCHITECTURE
    name=SXS_ASSEMBLY_NAME
    type="win32"
  />
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level='asInvoker' uiAccess='false' />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        name="Microsoft.Windows.Build.Appx.AppxPackaging.dll"
        version="0.0.0.0"/>
    </dependentAssembly>
  </dependency>
</assembly>
```


If there are issues other than this, Trace and Fix!

For now i think this one is CLOSED!

**Comment by jiansyuan** [comment]
> I want to address this issue,
> 
> A issue with the application's manifest file or its dependencies is usually indicated by the error message "The application has failed to start because its side-by-side configuration is incorrect". There are other potential causes for this, such as:
> 
> * Inaccurate Manifest File: There could be missing or inaccurate information in the manifest file. Make sure that all required assemblies and their versions are accurately specified in the manifest file.
> * Missing or Incorrect Dependencies: It is possible that the application is referring to assemblies that are either out-of-date or not present on the system.
> * Corrupted System Files: It is possible that corrupted system files exist that are connected to the side-by-side setup. System file checks can be used to find and address these problems.
> * Incorrect Installation: It's possible that the program or its dependencies weren't installed properly.
> 
> This problem also occurred to me. Upon closer inspection, I discovered that most of the time—on both my current and previous systems—the side-by-side configuration was altered inadvertently, and unless you run the corrected configuration once, it remains in the registry.
> 
> **Steps to produce trace : -**
> 
> CMD : `sxstrace trace -logfile:sxstrace.etl`
> 
> Run WSAppBak
> 
> Press ENTER or : `sxstrace stoptrace`
> 
> CMD : `sxstrace parse -logfile:sxstrace.etl -outfile:sxstrace.txt`
> 
> You'll find the 'sxstrace.txt' on your Desktop!
> 
> PRODUCED
> 
> ```
> =================
> Begin Activation Context Generation.
> Input Parameter:
> 	Flags = 0
> 	ProcessorArchitecture = AMD64
> 	CultureFallBacks = en-US;en
> 	ManifestPath = C:\Users\Administrator\Downloads\WSAppBak\WSAppBak\MakeAppx.exe.Manifest
> 	AssemblyDirectory = C:\Users\Administrator\Downloads\WSAppBak\WSAppBak\
> 	Application Config File = 
> -----------------
> INFO: Parsing Manifest File C:\Users\Administrator\Downloads\WSAppBak\WSAppBak\MakeAppx.exe.Manifest.
> 	INFO: Manifest Definition Identity is (null).
> 	ERROR: Line 8: The value SXS_ASSEMBLY_VERSION of attribute version in element assemblyIdentity is invalid.
> ERROR: Activation Context generation failed.
> End Activation Context Generation.
> 
> =================
> ```
> 
> To fix this and all sort of manifest issues, use dummy placeholders in "MakeAppx.exe.manifest" File
> 
> ```
> <?xml version='1.0' encoding='UTF-8' standalone='yes'?>
> <assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
>   <assemblyIdentity
>     version="1.0.0.0"
>     processorArchitecture="amd64"
>     name="MyAppName"
>     type="win32"
>   />
>   <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
>     <security>
>       <requestedPrivileges>
>         <requestedExecutionLevel level='asInvoker' uiAccess='false' />
>       </requestedPrivileges>
>     </security>
>   </trustInfo>
>   <dependency>
>     <dependentAssembly>
>       <assemblyIdentity
>         name="Microsoft.Windows.Build.Appx.AppxPackaging.dll"
>         version="0.0.0.0"/>
>     </dependentAssembly>
>   </dependency>
> </assembly>
> ```
> 
> Instead of :
> 
> ```
> <?xml version='1.0' encoding='UTF-8' standalone='yes'?>
> <assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
>   <assemblyIdentity
>     version=SXS_ASSEMBLY_VERSION
>     processorArchitecture=SXS_PROCESSOR_ARCHITECTURE
>     name=SXS_ASSEMBLY_NAME
>     type="win32"
>   />
>   <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
>     <security>
>       <requestedPrivileges>
>         <requestedExecutionLevel level='asInvoker' uiAccess='false' />
>       </requestedPrivileges>
>     </security>
>   </trustInfo>
>   <dependency>
>     <dependentAssembly>
>       <assemblyIdentity
>         name="Microsoft.Windows.Build.Appx.AppxPackaging.dll"
>         version="0.0.0.0"/>
>     </dependentAssembly>
>   </dependency>
> </assembly>
> ```
> 
> If there are issues other than this, Trace and Fix!
> 
> For now i think this one is CLOSED!

Thank you for your guidance last year on diagnosing the manifest error via sxstrace. Replacing the placeholder values in the manifest file as you suggested resolved the activation context issue completely. WSAppBak now runs as expected.
﻿
Belated but heartfelt thanks for your clear and actionable advice! I’ll close this issue now per your earlier note.
